# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6169c8a57abf39ff65f264dec329b99e4527af20411e64eabcacd23a74a5ff6617d4210513538bc077aaf86c9c9dce50fc610b2be5f4d4d3e3be1a394bd1ebc6

test:
  secret_key_base: 8520db5f6f011f15f3ad4537f71e6a16397f50ec102e2c0a456dbab41c0cb29cf8aea30819b63a7fb0b5b5e6fbe1f6baf8f81ce7320a50954f161672dc1e8b37

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
